### PR TITLE
Added dynamic tag and missing dependency

### PR DESCRIPTION
**Pull request by gf3**
Add dynamic tag to _anti-forgery-token_. Add clojure-contrib 1.2.0 to dependencies.

### CODE REVIEW

**Comment by weavejester** [comment]
Don't these commits contradict each other? The `:dynamic` tag only works with Clojure 1.3.0, whilst Clojure Contrib only works with Clojure 1.2.0.

**Comment by weavejester** [comment]
It also looks like the clojure.contrib.base64 dependency could be removed altogether.

**Comment by gf3** [comment]
Technically yes, the monolithic clojure-contrib is deprecated, however it still works in 1.3.0. Also yes, I didn't even notice that it's not being used. I should have simply removed it.

**Comment by weavejester** [comment]
Could you squash d106a79 and 7bd1e0d into one commit?

**Comment by weavejester** [comment]
Also, the "update:", "add:" and "remove:" prefixes aren't hugely useful, because they're rather arbitrary. If you could remove those as well, everything should be ready to merge :)

**Pull request closed without merging**
