### PR TITLE
Add anti-forgery-meta-tags helper to util namespace

### PR DESCRIPTION
**Pull request by RyanMcG**
Meta tags are helpful for setting request headers via JavaScript. I use this helper and I thought others might like it too.

### CODE REVIEW

**Comment by weavejester** [comment]
This seems a little specific. You'd need to write some Javascript for this to be of any use, and in that case, why not provide the token to Javascript directly? Is this targeting a particular Javascript framework?

**Comment by RyanMcG** [comment]
No framework in particular. I suppose this is just the way Rails does it so its the way I implemented it (originally did it a while ago).  Dumping it directly to javascript does make a bit more sense.  The only benefit to doing it with meta tags I can think of is you don't have to make a variable in the global namespace.  Do you think a helper to drop the token in as a variable in a JavaScript tag would be valuable?  I still do.

**Comment by weavejester** [comment]
Without the Javascript that reads the meta tag this helper doesn't actually provide anything useful. It's very specific to a particular mechanism, and to be honest I can't think of many advantages to using a meta tag over dumping it directly to a variable or object property.

**Comment by RyanMcG** [comment]
Yeah, to be clear I was agreeing with you before. I was just wondering if a helper to drop the token directly to JavaScript seemed like a good thing to you.

**Comment by weavejester** [comment]
What would the helper look like? Something like...

``` clojure
(defn script-token [var-name]
  (html (javascript-tag (str var-name " = " *anti-forgery-token*))))
```

?

**Comment by RyanMcG** [comment]
Ha, yeah. Pretty simple. Your version isn't valid javascript though since you need to wrap the token in quotes and probably want to end with a semicolon.

``` clojure
(defn script-token [& [var-name]]
  (html (javascript-tag (str (or var-name "CSRF_TOKEN") " = \"" *anti-forgery-token* "\";"))))
```

**Comment by RyanMcG** [comment]
I suppose you just want to close this? Feel free to reopen if you don't.

**Pull request closed without merging**
