### PR TITLE
Making ring-anti-forgery more customizable

### PR DESCRIPTION
**Pull request by babysnakes**
Hi

This is my shot at making ring-anti-forgery more customizable. The only default behavior I changed is that the wrapper checks PUT/DELETE requests as well as POST requests.

The following customizations are offered:
- A custom response (so it's possible to return a json response or nicer html).
- An alternative function to extract the token from the request (e.g. AngularJS uses a different method to handle tokens - it adds them to the request headers).

I don't know much about clojure and I know even less about security. I did my best at figuring out what the code is doing and I changed as little as I could to add these customizations. I hope I didn't introduce some security issue.

There is a small project I'm writing to learn clojure that is using this fork. It's available [here](http://github.com/babysnakes/ayler).

One last thing, If you accept this pull request you need to remove the note at the beginning of the readme file :smile: 

Thanks in advance

Haim

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the pull request. I can't merge it as-is, but I have taken a look through it, and I might be able to merge after cleaning up the commits. Currently this isn't high on my priority list, however, so it might be a while before I get round to it.

May I ask why you made it check PUT/DELETE events as well? As far as I know, no browser currently supports PUT/DELETE for forms, and all new proposals to introduce that behaviour provide the same protection as XHRs.

**Comment by babysnakes** [comment]
Thanks. I hope you'll find a way to merge it :)

As for the PUT/DELETE I may have been too trigger happy :(. I thought of the fact the javascript does support PUT/DELETE without thinking about the fact that browsers should not allow these requests from different origins. Should I revert it?

Bye

**Comment by babysnakes** [comment]
After another thought I think that flash is not subject to the same origin limitation. Maybe it's better to leave the PUT/DELETE checking?

**Comment by bluemont** [comment]
I looked over the pull request; it looks good to me. I can't speak to the PUT/DELETE issue. But why not merge in the other customization functionality?

**Comment by ddellacosta** [comment]
+1 on having a way to test against token in header, not just in POST params.  It would be great to at least merge that part in, although obviously I'm biased.

More to the point, would it be easier to break this up into a few separate issues in order to get functionality in more quickly?

**Comment by weavejester** [comment]
One of the main reason this pull request is still open is that I haven't had the time to integrate the functionality of this branch manually into ring-anti-forgery. The other reason is that I'm a little cautious about putting too much functionality into options.

I should have some time today to look into dealing with the current stack of pull requests, however.

**Comment by weavejester** [comment]
This functionality (with slightly different option names) is now in version 0.3.0.

**Comment by babysnakes** [comment]
Thanks :)

**Pull request closed without merging**
